"""multi-repo github: repo in unique key, pause and last-success

Revision ID: 0113be585e9d
Revises: 257058b421f5
Create Date: 2026-07-23 18:16:28.899415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0113be585e9d'
down_revision: Union[str, None] = '257058b421f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connections', sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('uq_connection_workspace_user_provider', table_name='connections')
    op.create_unique_constraint('uq_connection_workspace_user_provider_repo', 'connections', ['workspace_id', 'user_id', 'provider', 'repo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_connection_workspace_user_provider_repo', 'connections', type_='unique')
    op.create_index('uq_connection_workspace_user_provider', 'connections', ['workspace_id', 'user_id', 'provider'], unique=True)
    op.drop_column('connections', 'last_success_at')
    op.drop_column('connections', 'paused_at')
    # ### end Alembic commands ###
