"""add channel connections and resources

Revision ID: 1e96c156dcb2
Revises: 27c87fe3b7d3
Create Date: 2026-07-18 16:28:51.446176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e96c156dcb2'
down_revision: Union[str, None] = '27c87fe3b7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_connections',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'connection_id', name='uq_channel_connection')
    )
    op.create_index(op.f('ix_channel_connections_connection_id'), 'channel_connections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_channel_connections_team_id'), 'channel_connections', ['team_id'], unique=False)
    op.create_table('channel_connection_resources',
    sa.Column('channel_connection_id', sa.Uuid(), nullable=False),
    sa.Column('resource_key', sa.String(length=500), nullable=False),
    sa.Column('resource_label', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_connection_id'], ['channel_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_connection_id', 'resource_key', name='uq_channel_connection_resource')
    )
    op.create_index(op.f('ix_channel_connection_resources_channel_connection_id'), 'channel_connection_resources', ['channel_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_connection_resources_channel_connection_id'), table_name='channel_connection_resources')
    op.drop_table('channel_connection_resources')
    op.drop_index(op.f('ix_channel_connections_team_id'), table_name='channel_connections')
    op.drop_index(op.f('ix_channel_connections_connection_id'), table_name='channel_connections')
    op.drop_table('channel_connections')
    # ### end Alembic commands ###
