"""add channel ai history

Revision ID: 1f98a567756a
Revises: 1e96c156dcb2
Create Date: 2026-07-18 16:37:09.561739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f98a567756a'
down_revision: Union[str, None] = '1e96c156dcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_ai_history',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_ai_history_team_id'), 'channel_ai_history', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_ai_history_team_id'), table_name='channel_ai_history')
    op.drop_table('channel_ai_history')
    # ### end Alembic commands ###
