"""add meeting briefs

Revision ID: 208257541c40
Revises: 39dd0b640a85
Create Date: 2026-07-20 09:31:39.654455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '208257541c40'
down_revision: Union[str, None] = '39dd0b640a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_briefs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('event_external_id', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('prep_points', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'event_external_id', name='uq_meeting_brief_workspace_event')
    )
    op.create_index(op.f('ix_meeting_briefs_workspace_id'), 'meeting_briefs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_briefs_workspace_id'), table_name='meeting_briefs')
    op.drop_table('meeting_briefs')
    # ### end Alembic commands ###
