"""add attention items

Revision ID: 235321f84414
Revises: fb9d8ed9a68a
Create Date: 2026-07-19 06:09:06.154014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '235321f84414'
down_revision: Union[str, None] = 'fb9d8ed9a68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('IMPORTANT_EMAIL', 'UPCOMING_MEETING', 'STALE_PR', 'FINDING', 'MANUAL', name='attention_type'), nullable=False),
    sa.Column('origin', sa.Enum('DETECTED', 'MANUAL', name='attention_origin'), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'DONE', 'SNOOZED', 'DISMISSED', name='attention_state'), server_default='NEW', nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('why', sa.String(length=500), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'dedupe_key', name='uq_attention_workspace_dedupe')
    )
    op.create_index(op.f('ix_attention_items_workspace_id'), 'attention_items', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attention_items_workspace_id'), table_name='attention_items')
    op.drop_table('attention_items')
    # ### end Alembic commands ###
