"""action undo and autonomy policy

Revision ID: 257058b421f5
Revises: 94386042ad78
Create Date: 2026-07-22 18:59:59.302005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '257058b421f5'
down_revision: Union[str, None] = '94386042ad78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_policies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('enabled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enabled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'action_type', name='uq_action_policy_scope_type')
    )
    op.create_index(op.f('ix_action_policies_scope_key'), 'action_policies', ['scope_key'], unique=False)
    op.create_index(op.f('ix_action_policies_workspace_id'), 'action_policies', ['workspace_id'], unique=False)
    op.add_column('actions', sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('actions', sa.Column('undone_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('actions', sa.Column('undo_result', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'actions', 'users', ['undone_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'undo_result')
    op.drop_column('actions', 'undone_by_user_id')
    op.drop_column('actions', 'undone_at')
    op.drop_index(op.f('ix_action_policies_workspace_id'), table_name='action_policies')
    op.drop_index(op.f('ix_action_policies_scope_key'), table_name='action_policies')
    op.drop_table('action_policies')
    # ### end Alembic commands ###
