"""add channel roles and team creator

Revision ID: 27c87fe3b7d3
Revises: d58c1d2bae05
Create Date: 2026-07-18 16:18:23.032128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27c87fe3b7d3'
down_revision: Union[str, None] = 'd58c1d2bae05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_memberships', sa.Column('role', sa.Enum('CHANNEL_ADMIN', 'CHANNEL_MEMBER', name='channel_role'), server_default='CHANNEL_MEMBER', nullable=False))
    op.add_column('teams', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###

    # Grandfather clause, not an oversight: every row that already exists at
    # this exact moment predates Channel roles entirely - under the old
    # model, any of these members could already do anything in their channel
    # (no role concept existed to restrict them). Defaulting new column
    # additions to CHANNEL_MEMBER above and stopping there would silently
    # strip access nobody asked to have revoked. Any TeamMembership created
    # *after* this migration runs goes through join/invite/accept, which
    # already correctly default to CHANNEL_MEMBER in application code - this
    # UPDATE only touches rows that exist right now.
    op.execute("UPDATE team_memberships SET role = 'CHANNEL_ADMIN'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'created_by_user_id')
    op.drop_column('team_memberships', 'role')
    # ### end Alembic commands ###
