"""resource priority classification on connection

Revision ID: 297ed57ad033
Revises: ab0df589631d
Create Date: 2026-07-27 17:00:28.822036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '297ed57ad033'
down_revision: Union[str, None] = 'ab0df589631d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('priority', sa.Enum('CRITICAL', 'NORMAL', 'LOW', 'ARCHIVED', 'EXPERIMENTAL', name='resource_priority'), server_default='normal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'priority')
    # ### end Alembic commands ###
