"""shared connections at class and group level

Revision ID: 4f1484db5369
Revises: 63093ec9415e
Create Date: 2026-07-21 15:39:17.762484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f1484db5369'
down_revision: Union[str, None] = '63093ec9415e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_connections',
    sa.Column('scope_type', sa.Enum('CLASS', 'GROUP', name='shared_scope'), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', 'connection_id', name='uq_shared_connection_scope_conn')
    )
    op.create_index(op.f('ix_shared_connections_connection_id'), 'shared_connections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_shared_connections_scope_id'), 'shared_connections', ['scope_id'], unique=False)
    op.create_table('shared_connection_resources',
    sa.Column('shared_connection_id', sa.Uuid(), nullable=False),
    sa.Column('resource_key', sa.String(length=500), nullable=False),
    sa.Column('resource_label', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shared_connection_id'], ['shared_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_connection_id', 'resource_key', name='uq_shared_connection_resource')
    )
    op.create_index(op.f('ix_shared_connection_resources_shared_connection_id'), 'shared_connection_resources', ['shared_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_connection_resources_shared_connection_id'), table_name='shared_connection_resources')
    op.drop_table('shared_connection_resources')
    op.drop_index(op.f('ix_shared_connections_scope_id'), table_name='shared_connections')
    op.drop_index(op.f('ix_shared_connections_connection_id'), table_name='shared_connections')
    op.drop_table('shared_connections')
    # ### end Alembic commands ###
