"""add google provider and signal types

Revision ID: 5e907f8f2c91
Revises: b8305e16ae09
Create Date: 2026-07-17 11:16:28.601641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e907f8f2c91'
down_revision: Union[str, None] = 'b8305e16ae09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
