"""workspace classes and groups

Phase 2y: inserts two organizational levels between Workspace and Channel.

    Workspace -> Class -> Group -> Channel

Written by hand rather than autogenerated because of the backfill in the
middle: `teams.group_id` has to end up NOT NULL, but existing channels have
no Group to point at yet. So the column is added nullable, every existing
channel is adopted into a generated Class/Group, and only then is the
constraint tightened. An autogenerated migration would have gone straight to
NOT NULL and failed on any database that already has channels.

Existing channels land in a class named "General", inside a group named after
their old free-text `category` (or "General" when they had none). That column
was the closest thing to a grouping the old schema had, so honoring it
preserves whatever structure an admin had already expressed rather than
flattening everyone into one bucket.

Personal workspaces are skipped entirely - they hold no channels by design
(Phase 2x), so they get no Class and no Group.

Revision ID: 63093ec9415e
Revises: 860ad9df2053
Create Date: 2026-07-21 10:41:43.213597

"""

import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '63093ec9415e'
down_revision: Union[str, None] = '860ad9df2053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _slugify(value: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned or "general"


def upgrade() -> None:
    op.create_table(
        "workspace_classes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"]),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "slug", name="uq_class_workspace_slug"),
    )
    op.create_index(op.f("ix_workspace_classes_workspace_id"), "workspace_classes", ["workspace_id"])

    op.create_table(
        "workspace_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["class_id"], ["workspace_classes.id"]),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_id", "slug", name="uq_group_class_slug"),
    )
    op.create_index(op.f("ix_workspace_groups_class_id"), "workspace_groups", ["class_id"])

    # Nullable first so existing rows survive; tightened after the backfill.
    op.add_column("teams", sa.Column("group_id", sa.Uuid(), nullable=True))

    _backfill()

    op.alter_column("teams", "group_id", existing_type=sa.Uuid(), nullable=False)
    op.create_index(op.f("ix_teams_group_id"), "teams", ["group_id"])
    op.create_foreign_key("fk_teams_group_id", "teams", "workspace_groups", ["group_id"], ["id"])


def _backfill() -> None:
    connection = op.get_bind()
    now = datetime.now(timezone.utc)

    workspaces = connection.execute(
        sa.text(
            "SELECT DISTINCT t.workspace_id FROM teams t "
            "JOIN workspaces w ON w.id = t.workspace_id "
            "WHERE t.group_id IS NULL AND w.kind != 'PERSONAL'"
        )
    ).fetchall()

    for (workspace_id,) in workspaces:
        class_id = uuid.uuid4()
        connection.execute(
            sa.text(
                "INSERT INTO workspace_classes (id, workspace_id, name, slug, position, created_at) "
                "VALUES (:id, :workspace_id, 'General', 'general', 0, :created_at)"
            ),
            {"id": class_id.hex, "workspace_id": workspace_id, "created_at": now},
        )

        categories = connection.execute(
            sa.text("SELECT DISTINCT category FROM teams WHERE workspace_id = :ws AND group_id IS NULL"),
            {"ws": workspace_id},
        ).fetchall()

        for position, (category,) in enumerate(sorted(categories, key=lambda row: (row[0] or ""))):
            group_id = uuid.uuid4()
            group_name = (category or "General").strip() or "General"
            connection.execute(
                sa.text(
                    "INSERT INTO workspace_groups (id, class_id, name, slug, position, created_at) "
                    "VALUES (:id, :class_id, :name, :slug, :position, :created_at)"
                ),
                {
                    "id": group_id.hex, "class_id": class_id.hex, "name": group_name,
                    "slug": _slugify(group_name), "position": position, "created_at": now,
                },
            )
            if category is None:
                connection.execute(
                    sa.text(
                        "UPDATE teams SET group_id = :gid "
                        "WHERE workspace_id = :ws AND category IS NULL AND group_id IS NULL"
                    ),
                    {"gid": group_id.hex, "ws": workspace_id},
                )
            else:
                connection.execute(
                    sa.text(
                        "UPDATE teams SET group_id = :gid "
                        "WHERE workspace_id = :ws AND category = :cat AND group_id IS NULL"
                    ),
                    {"gid": group_id.hex, "ws": workspace_id, "cat": category},
                )

    # A channel in a Personal workspace shouldn't exist (Phase 2x removed the
    # surface), but a legacy row would block the NOT NULL below. Fail loudly
    # with the ids rather than inventing a home for it.
    orphans = connection.execute(sa.text("SELECT id, name FROM teams WHERE group_id IS NULL")).fetchall()
    if orphans:
        raise RuntimeError(
            "Channels could not be placed in the new hierarchy (likely in a Personal workspace): "
            + ", ".join(f"{name} ({tid})" for tid, name in orphans)
        )


def downgrade() -> None:
    op.drop_constraint("fk_teams_group_id", "teams", type_="foreignkey")
    op.drop_index(op.f("ix_teams_group_id"), table_name="teams")
    op.drop_column("teams", "group_id")
    op.drop_index(op.f("ix_workspace_groups_class_id"), table_name="workspace_groups")
    op.drop_table("workspace_groups")
    op.drop_index(op.f("ix_workspace_classes_workspace_id"), table_name="workspace_classes")
    op.drop_table("workspace_classes")
