"""add membership last seen

Revision ID: 6d420e904249
Revises: 235321f84414
Create Date: 2026-07-19 06:16:06.898906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d420e904249'
down_revision: Union[str, None] = '235321f84414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'last_seen_at')
    # ### end Alembic commands ###
