"""attention items carry their originating connection

Phase 3. An AttentionItem had no link back to the Connection whose data
produced it, so `channel_briefing` could only gate on *provider*: sharing an
admin's mailbox with a channel read as "this channel may see any Gmail in
this workspace", a member's private one included. Every other channel surface
(Feed, Insights, Knowledge, Prepare) already gates on `Signal.connection_id`;
this column lets attention be gated the same way.

Written by hand rather than autogenerated because of the backfill. Existing
rows are matched back to their source through `dedupe_key`, which encodes the
Signal's `external_id`:

    email:{external_id}      deadline:{external_id}
    pr:{external_id}         meeting:{external_id}:{YYYY-MM-DD}
    finding:{finding_id}     -> agent_runs.connection_id

Anything unmatched is deliberately left NULL. NULL is fail-closed at every
read site - such an item appears in no channel briefing and in no personal
list - so an unmatched row loses visibility rather than being guessed into
the wrong channel. `refresh_attention` rewrites `connection_id` from the live
Signal on every pass regardless of item state, so anything still real is
repaired within one sync cycle; rows whose underlying signal is already gone
stay NULL and are auto-completed by that same pass.

Revision ID: 741b13a66704
Revises: c7130ef9c30f
Create Date: 2026-07-22 15:46:53.373935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '741b13a66704'
down_revision: Union[str, None] = 'c7130ef9c30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("attention_items", sa.Column("connection_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_attention_items_connection_id"), "attention_items", ["connection_id"])
    op.create_foreign_key(
        "fk_attention_items_connection_id", "attention_items", "connections", ["connection_id"], ["id"]
    )

    _backfill()


def _backfill() -> None:
    connection = op.get_bind()

    # Signal-derived items. Strip the key's prefix - and, for meetings, the
    # trailing occurrence date - to recover the external_id. The workspace is
    # matched too, so an external_id that happens to repeat across workspaces
    # can never attribute an item to a connection in a different one.
    for prefix, external_id in (
        ("email:", "SUBSTRING(a.dedupe_key, 7)"),
        ("deadline:", "SUBSTRING(a.dedupe_key, 10)"),
        ("pr:", "SUBSTRING(a.dedupe_key, 4)"),
        ("meeting:", "SUBSTRING_INDEX(SUBSTRING(a.dedupe_key, 9), ':', 1)"),
    ):
        connection.execute(
            sa.text(
                f"""
                UPDATE attention_items a
                JOIN signals s
                  ON s.workspace_id = a.workspace_id
                 AND s.external_id = {external_id}
                SET a.connection_id = s.connection_id
                WHERE a.connection_id IS NULL
                  AND a.dedupe_key LIKE :pattern
                """
            ),
            {"pattern": f"{prefix}%"},
        )

    # Findings: the run already records which connection it examined. Ids are
    # stored as CHAR(32) hex while the dedupe key carries the dashed form.
    connection.execute(
        sa.text(
            """
            UPDATE attention_items a
            JOIN findings f ON f.id = REPLACE(SUBSTRING(a.dedupe_key, 9), '-', '')
            JOIN agent_runs r ON r.id = f.run_id
            SET a.connection_id = r.connection_id
            WHERE a.connection_id IS NULL
              AND a.dedupe_key LIKE 'finding:%'
            """
        )
    )


def downgrade() -> None:
    op.drop_constraint("fk_attention_items_connection_id", "attention_items", type_="foreignkey")
    op.drop_index(op.f("ix_attention_items_connection_id"), table_name="attention_items")
    op.drop_column("attention_items", "connection_id")
