"""channel required connections + revoked_at

Revision ID: 860ad9df2053
Revises: 8618a5c5494e
Create Date: 2026-07-21 10:04:49.889107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '860ad9df2053'
down_revision: Union[str, None] = '8618a5c5494e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_required_connections',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', 'GOOGLE_DRIVE', name='connection_provider'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('added_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'provider', name='uq_channel_required_connection')
    )
    op.create_index(op.f('ix_channel_required_connections_team_id'), 'channel_required_connections', ['team_id'], unique=False)
    op.add_column('connections', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'revoked_at')
    op.drop_index(op.f('ix_channel_required_connections_team_id'), table_name='channel_required_connections')
    op.drop_table('channel_required_connections')
    # ### end Alembic commands ###
