"""actions

Revision ID: 94386042ad78
Revises: fc972353ba12
Create Date: 2026-07-22 18:47:45.314100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94386042ad78'
down_revision: Union[str, None] = 'fc972353ba12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='action_risk'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'AWAITING_APPROVAL', 'APPROVED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'UNKNOWN', 'REJECTED', 'CANCELLED', name='action_status'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('verification', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_action_idempotency')
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_scope_key'), 'actions', ['scope_key'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_index(op.f('ix_actions_workspace_id'), 'actions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_workspace_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_scope_key'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
