"""widen provider and signal_type mysql enums

Revision ID: a57135e90e41
Revises: 5e907f8f2c91
Create Date: 2026-07-18 11:45:37.278939

Hand-written, not autogenerated: Alembic's autogenerate compares SQLAlchemy
Enum columns by name, not by member list, so adding GOOGLE_CALENDAR/GMAIL to
Provider and CALENDAR_EVENT/EMAIL to SignalType in the models produced an
empty migration (5e907f8f2c91) - the MySQL columns stayed at their original
enum('GITHUB') / enum('PR','REVIEW_SUBMITTED','COMMIT','ISSUE') definitions
until this migration actually widens them. Caught via a real "Data
truncated for column 'provider'" error inserting a GOOGLE_CALENDAR
connection, not caught by review - a good reminder that MySQL enum
changes always need to be checked by hand, autogenerate can't be trusted
for them.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a57135e90e41'
down_revision: Union[str, None] = '5e907f8f2c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'connections',
        'provider',
        existing_type=sa.Enum('GITHUB', name='connection_provider'),
        type_=sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', name='connection_provider'),
        existing_nullable=False,
    )
    op.alter_column(
        'signals',
        'type',
        existing_type=sa.Enum('PR', 'REVIEW_SUBMITTED', 'COMMIT', 'ISSUE', name='signal_type'),
        type_=sa.Enum('PR', 'REVIEW_SUBMITTED', 'COMMIT', 'ISSUE', 'CALENDAR_EVENT', 'EMAIL', name='signal_type'),
        existing_nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        'signals',
        'type',
        existing_type=sa.Enum('PR', 'REVIEW_SUBMITTED', 'COMMIT', 'ISSUE', 'CALENDAR_EVENT', 'EMAIL', name='signal_type'),
        type_=sa.Enum('PR', 'REVIEW_SUBMITTED', 'COMMIT', 'ISSUE', name='signal_type'),
        existing_nullable=False,
    )
    op.alter_column(
        'connections',
        'provider',
        existing_type=sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', name='connection_provider'),
        type_=sa.Enum('GITHUB', name='connection_provider'),
        existing_nullable=False,
    )
