"""situations

Revision ID: a8c3d534f0c6
Revises: e0d9707fcd76
Create Date: 2026-07-22 16:43:28.792332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8c3d534f0c6'
down_revision: Union[str, None] = 'e0d9707fcd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('situation_key', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('SERVICE_JEOPARDY', 'MEETING_UNPREPARED', name='situation_kind'), nullable=False),
    sa.Column('status', sa.Enum('EMERGING', 'ACTIVE', 'RESOLVED', name='situation_status'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('what_is_developing', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('suggested_next_steps', sa.JSON(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'situation_key', name='uq_situation_scope_key')
    )
    op.create_index(op.f('ix_situations_scope_key'), 'situations', ['scope_key'], unique=False)
    op.create_index(op.f('ix_situations_workspace_id'), 'situations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_situations_workspace_id'), table_name='situations')
    op.drop_index(op.f('ix_situations_scope_key'), table_name='situations')
    op.drop_table('situations')
    # ### end Alembic commands ###
