"""github account login on connection

Revision ID: ab0df589631d
Revises: 0113be585e9d
Create Date: 2026-07-23 18:18:20.450299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab0df589631d'
down_revision: Union[str, None] = '0113be585e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('github_login', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'github_login')
    # ### end Alembic commands ###
