"""workspace-tier sharing and channel exclusions

Revision ID: c7130ef9c30f
Revises: 4f1484db5369
Create Date: 2026-07-22 06:01:05.296512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7130ef9c30f'
down_revision: Union[str, None] = '4f1484db5369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate does NOT detect a new member on an existing Enum column -
    # it only diffs tables. Without this ALTER the column stays
    # enum('CLASS','GROUP') and every workspace-tier share fails on insert
    # with a data-truncation error. Verified against the live schema before
    # writing this.
    op.execute("ALTER TABLE shared_connections MODIFY scope_type ENUM('WORKSPACE','CLASS','GROUP') NOT NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_connection_exclusions',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('excluded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['excluded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'connection_id', name='uq_channel_connection_exclusion')
    )
    op.create_index(op.f('ix_channel_connection_exclusions_connection_id'), 'channel_connection_exclusions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_channel_connection_exclusions_team_id'), 'channel_connection_exclusions', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_connection_exclusions_team_id'), table_name='channel_connection_exclusions')
    op.drop_index(op.f('ix_channel_connection_exclusions_connection_id'), table_name='channel_connection_exclusions')
    op.drop_table('channel_connection_exclusions')
    # ### end Alembic commands ###

    # Any workspace-tier shares must go before the enum can narrow again,
    # or the rows become unrepresentable.
    op.execute("DELETE FROM shared_connections WHERE scope_type = 'WORKSPACE'")
    op.execute("ALTER TABLE shared_connections MODIFY scope_type ENUM('CLASS','GROUP') NOT NULL")
