"""situations are investigable directly

Revision ID: ca7feae6dfc5
Revises: a8c3d534f0c6
Create Date: 2026-07-22 17:05:56.679303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'ca7feae6dfc5'
down_revision: Union[str, None] = 'a8c3d534f0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('situation_id', sa.Uuid(), nullable=True))
    op.alter_column('investigations', 'attention_item_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.create_index(op.f('ix_investigations_situation_id'), 'investigations', ['situation_id'], unique=False)
    op.create_unique_constraint('uq_investigation_situation_scope', 'investigations', ['situation_id', 'scope_key'])
    op.create_foreign_key(None, 'investigations', 'situations', ['situation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_constraint('uq_investigation_situation_scope', 'investigations', type_='unique')
    op.drop_index(op.f('ix_investigations_situation_id'), table_name='investigations')
    op.alter_column('investigations', 'attention_item_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_column('investigations', 'situation_id')
    # ### end Alembic commands ###
