"""add email_summaries table

Revision ID: ca9a314a4e8f
Revises: a57135e90e41
Create Date: 2026-07-18 08:21:00.475160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca9a314a4e8f'
down_revision: Union[str, None] = 'a57135e90e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_summaries',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('sender', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'message_id', name='uq_email_summary_workspace_message')
    )
    op.create_index(op.f('ix_email_summaries_workspace_id'), 'email_summaries', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_summaries_workspace_id'), table_name='email_summaries')
    op.drop_table('email_summaries')
    # ### end Alembic commands ###
