"""add google_drive provider

Revision ID: d58c1d2bae05
Revises: ca9a314a4e8f
Create Date: 2026-07-18 08:40:53.944932

Hand-written, not autogenerated - see a57135e90e41's docstring for why:
Alembic's autogenerate compares MySQL Enum columns by name, not member
list, so adding GOOGLE_DRIVE to the Provider enum needs the widen done by
hand, verified after with SHOW COLUMNS, same as every enum change since.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd58c1d2bae05'
down_revision: Union[str, None] = 'ca9a314a4e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'connections',
        'provider',
        existing_type=sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', name='connection_provider'),
        type_=sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', 'GOOGLE_DRIVE', name='connection_provider'),
        existing_nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        'connections',
        'provider',
        existing_type=sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', 'GOOGLE_DRIVE', name='connection_provider'),
        type_=sa.Enum('GITHUB', 'GOOGLE_CALENDAR', 'GMAIL', name='connection_provider'),
        existing_nullable=False,
    )
