"""commitments

Revision ID: d95566f286ff
Revises: ca7feae6dfc5
Create Date: 2026-07-22 17:23:31.876249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd95566f286ff'
down_revision: Union[str, None] = 'ca7feae6dfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('commitment_key', sa.String(length=300), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'TRACKED', name='commitment_source'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DUE_SOON', 'AT_RISK', 'OVERDUE', 'RESOLVED', 'DISMISSED', name='commitment_status'), nullable=False),
    sa.Column('what', sa.String(length=500), nullable=False),
    sa.Column('owner_label', sa.String(length=200), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('source_signal_id', sa.Uuid(), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'commitment_key', name='uq_commitment_scope_key')
    )
    op.create_index(op.f('ix_commitments_scope_key'), 'commitments', ['scope_key'], unique=False)
    op.create_index(op.f('ix_commitments_workspace_id'), 'commitments', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitments_workspace_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_scope_key'), table_name='commitments')
    op.drop_table('commitments')
    # ### end Alembic commands ###
