"""investigations

Revision ID: e0d9707fcd76
Revises: 741b13a66704
Create Date: 2026-07-22 16:16:38.806107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0d9707fcd76'
down_revision: Union[str, None] = '741b13a66704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('attention_item_id', sa.Uuid(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('what_happened', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attention_item_id'], ['attention_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attention_item_id', 'scope_key', name='uq_investigation_item_scope')
    )
    op.create_index(op.f('ix_investigations_attention_item_id'), 'investigations', ['attention_item_id'], unique=False)
    op.create_index(op.f('ix_investigations_workspace_id'), 'investigations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_workspace_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_attention_item_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
