"""goals

Revision ID: f812c916c292
Revises: 9cf969a28a4a
Create Date: 2026-07-22 18:17:56.334414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f812c916c292'
down_revision: Union[str, None] = '9cf969a28a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.Enum('UNKNOWN', 'ON_TRACK', 'AT_RISK', 'BLOCKED', 'ACHIEVED', 'ABANDONED', name='goal_health'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('health_reasons', sa.JSON(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('state_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_scope_key'), 'goals', ['scope_key'], unique=False)
    op.create_index(op.f('ix_goals_workspace_id'), 'goals', ['workspace_id'], unique=False)
    op.create_table('goal_commitments',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('commitment_id', sa.Uuid(), nullable=False),
    sa.Column('linked_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'commitment_id', name='uq_goal_commitment')
    )
    op.create_index(op.f('ix_goal_commitments_commitment_id'), 'goal_commitments', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_goal_commitments_goal_id'), 'goal_commitments', ['goal_id'], unique=False)
    op.add_column('investigations', sa.Column('goal_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_investigations_goal_id'), 'investigations', ['goal_id'], unique=False)
    op.create_unique_constraint('uq_investigation_goal_scope', 'investigations', ['goal_id', 'scope_key'])
    op.create_foreign_key(None, 'investigations', 'goals', ['goal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.drop_constraint('uq_investigation_goal_scope', 'investigations', type_='unique')
    op.drop_index(op.f('ix_investigations_goal_id'), table_name='investigations')
    op.drop_column('investigations', 'goal_id')
    op.drop_index(op.f('ix_goal_commitments_goal_id'), table_name='goal_commitments')
    op.drop_index(op.f('ix_goal_commitments_commitment_id'), table_name='goal_commitments')
    op.drop_table('goal_commitments')
    op.drop_index(op.f('ix_goals_workspace_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_scope_key'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
