"""add channel metadata privacy archive

Revision ID: fb9d8ed9a68a
Revises: 1f98a567756a
Create Date: 2026-07-19 05:24:01.816589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb9d8ed9a68a'
down_revision: Union[str, None] = '1f98a567756a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('icon', sa.String(length=16), nullable=True))
    op.add_column('teams', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('privacy', sa.Enum('PUBLIC', 'INVITE_ONLY', 'PRIVATE', name='channel_privacy'), server_default='PUBLIC', nullable=False))
    op.add_column('teams', sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_archived')
    op.drop_column('teams', 'privacy')
    op.drop_column('teams', 'category')
    op.drop_column('teams', 'icon')
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
