"""goal relevance and weights

Revision ID: fc972353ba12
Revises: f812c916c292
Create Date: 2026-07-22 18:34:46.805537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc972353ba12'
down_revision: Union[str, None] = 'f812c916c292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_situations',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('situation_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('UNRELATED', 'RELATED', 'RISK', 'BLOCKING', name='goal_relation'), nullable=False),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('set_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['situation_id'], ['situations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'situation_id', name='uq_goal_situation')
    )
    op.create_index(op.f('ix_goal_situations_goal_id'), 'goal_situations', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_situations_situation_id'), 'goal_situations', ['situation_id'], unique=False)
    op.add_column('goal_commitments', sa.Column('weight', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_commitments', 'weight')
    op.drop_index(op.f('ix_goal_situations_situation_id'), table_name='goal_situations')
    op.drop_index(op.f('ix_goal_situations_goal_id'), table_name='goal_situations')
    op.drop_table('goal_situations')
    # ### end Alembic commands ###
