/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConnectionsIndexRouteImport } from './routes/connections/index'
import { Route as ConnectionsProviderRouteImport } from './routes/connections/$provider'
import { Route as FindingsIndexRouteImport } from './routes/findings/index'
import { Route as FindingsIdRouteImport } from './routes/findings/$id'
import { Route as SituationsIndexRouteImport } from './routes/situations/index'
import { Route as SituationsIdRouteImport } from './routes/situations/$id'
import { Route as WorkspaceServiceRouteImport } from './routes/workspace/$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsProviderRoute = ConnectionsProviderRouteImport.update({
  id: '/connections/$provider',
  path: '/connections/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIdRoute = FindingsIdRouteImport.update({
  id: '/findings/$id',
  path: '/findings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsIndexRoute = SituationsIndexRouteImport.update({
  id: '/situations/',
  path: '/situations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsIdRoute = SituationsIdRouteImport.update({
  id: '/situations/$id',
  path: '/situations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceServiceRoute = WorkspaceServiceRouteImport.update({
  id: '/workspace/$service',
  path: '/workspace/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/connections/$provider': typeof ConnectionsProviderRoute
  '/findings/$id': typeof FindingsIdRoute
  '/situations/$id': typeof SituationsIdRoute
  '/workspace/$service': typeof WorkspaceServiceRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/findings/': typeof FindingsIndexRoute
  '/situations/': typeof SituationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/connections/$provider': typeof ConnectionsProviderRoute
  '/findings/$id': typeof FindingsIdRoute
  '/situations/$id': typeof SituationsIdRoute
  '/workspace/$service': typeof WorkspaceServiceRoute
  '/connections': typeof ConnectionsIndexRoute
  '/findings': typeof FindingsIndexRoute
  '/situations': typeof SituationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/connections/$provider': typeof ConnectionsProviderRoute
  '/findings/$id': typeof FindingsIdRoute
  '/situations/$id': typeof SituationsIdRoute
  '/workspace/$service': typeof WorkspaceServiceRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/findings/': typeof FindingsIndexRoute
  '/situations/': typeof SituationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/memory'
    | '/settings'
    | '/connections/$provider'
    | '/findings/$id'
    | '/situations/$id'
    | '/workspace/$service'
    | '/connections/'
    | '/findings/'
    | '/situations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/memory'
    | '/settings'
    | '/connections/$provider'
    | '/findings/$id'
    | '/situations/$id'
    | '/workspace/$service'
    | '/connections'
    | '/findings'
    | '/situations'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/memory'
    | '/settings'
    | '/connections/$provider'
    | '/findings/$id'
    | '/situations/$id'
    | '/workspace/$service'
    | '/connections/'
    | '/findings/'
    | '/situations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  ConnectionsProviderRoute: typeof ConnectionsProviderRoute
  FindingsIdRoute: typeof FindingsIdRoute
  SituationsIdRoute: typeof SituationsIdRoute
  WorkspaceServiceRoute: typeof WorkspaceServiceRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  SituationsIndexRoute: typeof SituationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$provider': {
      id: '/connections/$provider'
      path: '/connections/$provider'
      fullPath: '/connections/$provider'
      preLoaderRoute: typeof ConnectionsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$id': {
      id: '/findings/$id'
      path: '/findings/$id'
      fullPath: '/findings/$id'
      preLoaderRoute: typeof FindingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/': {
      id: '/situations/'
      path: '/situations'
      fullPath: '/situations/'
      preLoaderRoute: typeof SituationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations/$id': {
      id: '/situations/$id'
      path: '/situations/$id'
      fullPath: '/situations/$id'
      preLoaderRoute: typeof SituationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$service': {
      id: '/workspace/$service'
      path: '/workspace/$service'
      fullPath: '/workspace/$service'
      preLoaderRoute: typeof WorkspaceServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  ConnectionsProviderRoute: ConnectionsProviderRoute,
  FindingsIdRoute: FindingsIdRoute,
  SituationsIdRoute: SituationsIdRoute,
  WorkspaceServiceRoute: WorkspaceServiceRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  SituationsIndexRoute: SituationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
